modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="bettervillagertrades"
version="${version}"
displayName="BetterVillagerTrades"
authors="brainage04"
description='''Rerolls untraded villagers, protects player-selected trades, and guarantees max-level enchantment outputs.'''
[[mixins]]
config="bettervillagertrades.mixins.json"

[[dependencies.bettervillagertrades]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.bettervillagertrades]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},26.3)"
ordering="NONE"
side="BOTH"
